name: GeneratePDF

on:
  push:
    branches:
      - main

jobs:
  generatePdf:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: install Chrome
        run: sudo apt install -y chromium-browser
        
      - name: Install dependencies
        run: yarn
      
      - name: BUILD
        run: yarn build

      - name: Generate&UpdatePDF
        run: node dist/index.js 
