name: GeneratePDF

on:
  push:
    branches:
      - dev

jobs:
  generatePdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: ./

      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Generate PDF Action
        uses: ashuvssut/generatePdf-GHA@v2.7
        with:
          GITHUB_TOKEN: ${{secrets.MY_TOKEN}}
