name: GeneratePDF

on:
  push:
    branches:
      - main

jobs:
  generatePdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: ./

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Generate PDF Action
        uses: ashuvssut/generatePdf-GHA@v1.3-alpha
        with:
          GITHUB_TOKEN: ${{secrets.MY_TOKEN}}
